name: CD

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      app-name:
        required: true
        type: string

jobs:
  set-artifact-version:
    runs-on: ubuntu-22.04
    outputs:
      artifact-version: ${{ steps.set-artifact-version.outputs.artifact-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Set artifact version
        id: set-artifact-version
        run: |
          if [ "${{ github.event.inputs.targetEnvironment }}" != "" ]; then
            echo "artifact-version=test-next" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Get the latest tag for the project considering the current commit and excluding the current tag that triggered the workflow
          LATEST_TAG=$(git describe --tags --abbrev=0 --match "${{ inputs.app-name }}/*" --exclude "${{ github.ref_name }}" "${{ github.sha }}" 2>/dev/null \
            | sed 's/^${{ inputs.app-name }}\///')
          if [ -z "$LATEST_TAG" ]; then
            LATEST_TAG="v0.0.0"
          fi
          echo "artifact-version=${LATEST_TAG}-next" >> $GITHUB_OUTPUT

  deploy:
    needs: [set-artifact-version]
    runs-on: ubuntu-22.04
    env:
      APP_ENV: ${{ github.event.inputs.targetEnvironment != '' && github.event.inputs.targetEnvironment || (startsWith(github.ref, 'refs/tags/') && 'live' || 'stage' )}}
    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd ${{ inputs.working-directory }}
          APP_VERSION=${{ needs.set-artifact-version.outputs.artifact-version }}
          echo "Add your deploy step here (e.g. `cdk deploy -c app_version=$APP_VERSION`)"
